.TH Q_OPCODES 5 "21 Dec 2018" q-54 "q"
.SH NAME
Q opcodes - the Q ALU opcodes
.SH DESCRIPTION
.TP
.B Architecture of the Run Machine
.br
Start \fBq\fR and enter \fBH ALU\fR
.br
.TP
.B List of opcodes
.br
Enter \fBq\ \&-A\fR at the shell prompt or from within \fBq\fR to get a list.
From the shell prompt the output may be fed into a pager,
e.g. \fBq -A | less -X\fR
