#!/bin/bash -p
# Test headers for needing to include headers
#set -x
[ $# -eq 1 ]|| { echo "Must have 1 header file as argument" >&2; return 1; }
F=$(tempfile)
cat >$F <<////
#include "$1"
int main (int argc, char **argv)
{
  return 0;
}
////
mv $F $F.c
gcc -Wall -Wstrict-prototypes -Wmissing-prototypes -I .. $F.c
rm -f $F.c a.out
