#!/bin/sh
q -onvifm+q^Ju,55.1^Jq^J </dev/null
q -onvifm+q^Ju,55.11^Jq^J </dev/null
#q -nvifm+q^Ju,55.11a^Jq^J # Must run this script interactively
q -onvifm+q^Ju,55.13^Jq^J </dev/null
q -onvifm+q^Ju,55.15^Jq^J </dev/null
q -onvifm+q^Ju,55.32^Jq^J </dev/null
q -onvifm+q^Ju,56.062^Jq^J </dev/null
q -onvifm+q^Ju,56.064^Jq^J </dev/null
q -onvifm+q^Ju,56.202^Jq^J </dev/null
q -onvifm+q^Ju,56.203^Jq^J </dev/null
q -onvifm+q^Ju,56.43^Jq^J </dev/null
q -onvifm+q^Ju,56.48^Jq^J </dev/null
q -onvifm+q^Ju,56.49^Jq^J </dev/null
