#!/bin/sh
q -onvifm+q^Ju,55.1^Jq^J </dev/null
q -onvifm+q^Ju,55.11^Jq^J </dev/null
#q -nvifm+q^Ju,55.11a^Jq^J
q -onvifm+q^Ju,55.13^Jq^J </dev/null
q -onvifm+q^Ju,55.15^Jq^J </dev/null
# 55.32 exits q so m.b. last test
q -onvifm+q^Ju,55.32^Jq^J </dev/null
